# Vectors and Matrices
Time to work! Do it with numpy first and then if you have time, manually by hand :)

## Vectors

In [ ]:
Lists can be used to represent mathematical vectors. In this exercise and several that follow you will write functions to perform standard operations on vectors. Create a file named vectors.py or use the Jupyter notebook provided

Write a function add_vectors(u, v) that takes two lists of numbers of the same length, and returns a new list containing the sums of the corresponding elements of each.

**Note that the text in """ """ is provided for you to accurately verify that your function works :)**

In [14]:
import numpy as np

def add_vectors(u, v):
  
  #using numpy module
  return np.add(u, v)
  
  #manually calculation
  '''
  sum_vectors = []
  if len(u) != len(v):
    print('Error! Cannot operate with different shapes')
  else:
    for i in range(len(u)):
      sum_vectors.append(u[i] + v[i])
    return sum_vectors
  '''
add_vectors([1, 0], [1, 1])

array([2, 1])

Write a function scalar_mult(s, v) that takes a number, s, and a list, v and returns the [scalar multiple](https://en.wikipedia.org/wiki/Scalar_multiplication) of v by s.

In [18]:
def scalar_mult(s, v):
  #using numpy
  return np.dot(s, v)

  #manually
  '''
  scalar_result = []
  for i in v:
    scalar_result.append(i * s)
  return scalar_result
  '''

scalar_mult(5, [1, 2])

[5, 10]

Write a function dot_product(u, v) that takes two lists of numbers of the same length, and returns the sum of the products of the corresponding elements of each (the [dot_product](https://en.wikipedia.org/wiki/Dot_product).

In [27]:
def dot_product(u, v):
  #using numpy
  return np.dot(u, v)
  
  #manually
  '''
  result = 0
  if len(u) != len(v):
    print('Error! Cannot not do the operation')
  else:
    for i in range(len(u)):
      result += u[i] * v[i]
  return result
  '''
dot_product([1, 2, 1], [1, 4, 3])

'\n       dot_product([1, 1], [1, 1])\n      2\n       dot_product([1, 2], [1, 4])\n      9\n       dot_product([1, 2, 1], [1, 4, 3])\n      12\n    dot_product([2, 0, -1, 1], [1, 5, 2, 0])\n      0\n'

## Matrices

Create a new module named matrices.py or *use the Jupyter notebook provided* and add the following function, which returns a copy of nested lists of numbers such that the lists are not aliases:

In [4]:
def copy_matrix(matrix):
  return np.copy(matrix)
    """
      >>> copy_matrix([[1, 2], [3, 4]])
      [[1, 2], [3, 4]]
      >>> copy_matrix([[1, 2, 3], [4, 5, 6]])
      [[1, 2, 3], [4, 5, 6]]
      >>> copy_matrix([[1, 2], [3, 4], [5, 6], [7, 8]])
      [[1, 2], [3, 4], [5, 6], [7, 8]]
      >>> m = [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
      >>> copyofm = copy_matrix(m)
      >>> copyofm
      [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
      >>> for row_num, row in enumerate(copyofm):
      ...     for col_num, col_val in enumerate(row):
      ...         copyofm[row_num][col_num] = 42
      ...
      >>> copyofm
      [[42, 42, 42], [42, 42, 42], [42, 42, 42]]
      >>> m
      [[1, 0, 0], [0, 2, 0], [0, 0, 3]]
    """
    pass
copy_matrix([[1, 2], [3, 4]])

In [34]:
def add_row(matrix, row):
  #using numpy
  return np.vstack([matrix, row])

add_row([[0, 0], [0, 0]], [0, 0])

array([[0, 0],
       [0, 0],
       [0, 0]])

In [35]:
def add_column(matrix, column):
  #using numpy
  return np.append(matrix, column, axis=1)
  
add_column([[0, 0], [0, 0]], [[0], [0]])

array([[0, 0, 0],
       [0, 0, 0]])

Write a function add_matrices(m1, m2) that adds m1 and m2 and returns a new matrix containing their sum. You can assume that m1 and m2 are the same size. You add two matrices by adding their corresponding values.

In [41]:
def add_matrices(m1, m2):
  return m1 + m2

a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 2], [2, 2]])
add_matrices(a, b)

array([[3, 4],
       [5, 6]])

Write a function scalar_mult(s, m) that multiplies a matrix, m, by a scalar, s.

In [42]:
def scalar_mult(s, m):
  return s * m
    
a = np.array([[1, 2], [3, 4]])
scalar_mult(3, a)

array([[ 3,  6],
       [ 9, 12]])

Write functions row_times_column and matrix_mult:

In [10]:
def row_times_column(m1, row, m2, column):
    """
      >>> row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 0)
      19
      >>> row_times_column([[1, 2], [3, 4]], 0, [[5, 6], [7, 8]], 1)
      22
      >>> row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 0)
      43
      >>> row_times_column([[1, 2], [3, 4]], 1, [[5, 6], [7, 8]], 1)
      50
    """
    pass

In [13]:
def matrix_mult(m1, m2):
    """
      >>> matrix_mult([[1, 2], [3,  4]], [[5, 6], [7, 8]])
      [[19, 22], [43, 50]]
      >>> matrix_mult([[1, 2, 3], [4,  5, 6]], [[7, 8], [9, 1], [2, 3]])
      [[31, 19], [85, 55]]
      >>> matrix_mult([[7, 8], [9, 1], [2, 3]], [[1, 2, 3], [4, 5, 6]])
      [[39, 54, 69], [13, 23, 33], [14, 19, 24]]
    """
    pass

Write a function transpose that takes a matrix as an argument and returns is transpose:

In [45]:
def transpose(m):
  return m.T
    
m = np.array([[3, 4, 6]])
transpose(m)

array([[3],
       [4],
       [6]])